### ISSUE TITLE
Auth fails when using secret instead of username and password

### ISSUE THREAD

**Issue by mylesagray** [kubernetes/cloud-provider-vsphere#210]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When using a secret to store creds, if the base64 string is not generated using exactly the format: `echo -n P@ssw0rd | base64` auth will fail.

I.E: if I do `echo P@ssw0rd | base64` - auth fails.

**What you expected to happen**:
Expect CCM to handle a new line at the end of the password, this will be a common stumbling block for users.

**How to reproduce it (as minimally and precisely as possible)**:
Base64 encode password:

```sh
$ echo P@ssw0rd | base64
UEBzc3cwcmQK
```

Add to `vccreds.yaml`:

```yaml
apiVersion: v1
kind: Secret
metadata:
 name: vc-creds
type: Opaque
data:
   10.198.16.4.password: UEBzc3cwcmQK
   10.198.16.4.username: YWRtaW5pc3RyYXRvckB2c3BoZXJlLmxvY2Fs
```

Deploy CCM - auth fails, repeat above with `-n` flag, it will succeed.

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version: master
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools: Kubeadm
