### ISSUE TITLE
Running vmtoolsd inside pod will change worker node's internalIP

### ISSUE THREAD

**Issue by lynic** [kubernetes/cloud-provider-vsphere#353]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Worker node's internalIP and externalIP was changed after running another vmtoolsd inside pod.

**What you expected to happen**:
It won't change the internalIP and externalIP.

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod on one worker node, and run vmtoolsd inside pod. 
It will report the pod's IP/FQDN information to VC.
Wait for a while, run `kubectl get nodes -owide` . We can see that the node's internalIP and externalIP change to pod's IP.

**Anything else we need to know?**:
We don't set  --node-ip with kubelet, cloud-provider=external .
This pod requests following sys capabilities:
```
    securityContext:
      capabilities:
        add:
        - SYS_TIME
        - SYS_ADMIN
        - SYS_NICE
        - NET_ADMIN
        - NET_RAW
        - SYS_PACCT
        - IPC_LOCK
        - IPC_OWNER
        - AUDIT_WRITE
        - AUDIT_CONTROL
        - SYS_PTRACE
        - SYS_RESOURCE
```

**Environment**:
- vsphere-cloud-controller-manager version:
v1.1.0_vmware.2
- OS (e.g. from /etc/os-release):
photon 3

- Kernel (e.g. `uname -a`):
4.19.115-3.ph3

- Install tools:
vmtoolsd
- Others:
k8s 1.18.2
