### ISSUE TITLE
vsphere-cpi chart fails when service is enabled

### ISSUE THREAD

**Issue by bitnik** [kubernetes/cloud-provider-vsphere#509]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The `vsphere-cpi` chart deployment fails when service is enabled (`service.enabled`). `vsphere-cpi` pods stuck in "CreateContainerConfigError" state and when I describe a `vsphere-cpi` pod I see `Error: configmap "vsphere-cpi" not found` error.

**What you expected to happen**:

The `vsphere-cpi` chart is deployed successfully when service is enabled.

**How to reproduce it (as minimally and precisely as possible)**:

Enable service in your config yaml and deploy the chart.

```yaml
service:
  enabled: true
```

**Anything else we need to know?**:

As a workaround I created a configmap as 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vsphere-cpi
  labels:
    app: vsphere-cpi
    vsphere-cpi-infra: common-configmap
    component: cloud-controller-manager
    release: vsphere-cpi
  namespace: "vsphere-cpi-ns"
data:
  api.binding: ":43001"
```

and then it worked.

I think the fix would be replacing

https://github.com/kubernetes/cloud-provider-vsphere/blob/afebb9e86d603719c350aac17c65cea88fd4d7e1/charts/vsphere-cpi/templates/daemonset.yaml#L84-L88

with

```yaml
          - name: VSPHERE_API_BINDING
            value: {{ template "api.binding" . }}
```

If you aggree, I can create the PR.

**Environment**:
- vsphere-cpi chart version: 1.0.0 (appVersion: 1.21.0)
- Install tools: helm v3.7.0
