### ISSUE TITLE
vSphere CPI should be configurable with a server in the format of an IPv6 address 

### ISSUE THREAD

**Issue by tylerschultz** [kubernetes/cloud-provider-vsphere#640]
### What happened?

When attempting to create a Kubernetes Secret in the format the vSphere CPI expects, with an IPv6 address, causes Kubernetes to error. The vSphere CPI expects the credentials Secret keys to contain the vSphere server address. IPv6 addresses contain colons, which are invalid Secret key characters. This forces users to use a DNS address when configuring in an IPv6 environment.

### What did you expect to happen?

I expect the server to accept Secret data in a format that is friendly to IPv6 addresses.

### How can we reproduce it (as minimally and precisely as possible)?

```
$ cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-credentials
stringData:
  "fd01::1.username": "user"
  "fd01::1.password": "sekret"
type: Opaque
EOF
The Secret "vsphere-credentials" is invalid:
* data[fd01::1.password]: Invalid value: "fd01::1.password": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
* data[fd01::1.username]: Invalid value: "fd01::1.username": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

### Anything else we need to know (please consider providing level 4 or above logs of CPI)?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}```

</details>


### Cloud provider or hardware configuration

<details>
vsphere-cpi version 1.23.1
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux kangaroo 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Kernel (e.g. `uname -a`)

<details>
Linux kangaroo 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
</details>

### Install tools

<details>
carvel packaging
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Others

<details>

</details>

**Comment by tylerschultz** [comment]
We propose a secret format that looks something like this:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-vsphere-credentials
  namespace: kube-system
stringData:
  credentials:
  - server: 'fd01::1'
    password": "potato"
    username": "bigbird"
  - server: 'fd01::2'
    password": "cookie"
    username": "monster"
type: Opaque
```

When parsing the secret, a check could be made for the `credentials` key, if if present expect the above format, else falling back to the existing secret parsing logic.

We're happy to PR this if it's found to be an acceptable approach.

**Comment by christianang** [comment]
Realized that the above also doesn't work because secrets are key value pairs. So `credentials` can't be an array. New proposal, use a suffix that can group server, username, and password together:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-vsphere-credentials
  namespace: kube-system
stringData:
  server_0: 'fd01::1'
  password_0: "potato"
  username_0: "bigbird"
  server_1: 'fd01::2'
  password_1: "cookie"
  username_1: "monster"
type: Opaque
```
